=== dkreda/MyPerlProject/Integration/Projects/SwimConvertor/CAFTests/UAF.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 (http://www.altova.com) by XMLSpy 2007 Professional Ed., Installed for 43 users (Comvers) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="SWIM">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="UnitType">
					<xs:complexType>
						<xs:all>
							<xs:element name="Install" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Component" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="OnlyOn" minOccurs="0">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="UnitName" maxOccurs="unbounded">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:minLength value="1"/>
																			<xs:pattern value="(\S.*\S)|(\S*)"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="Name" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:minLength value="1"/>
															<xs:pattern value="(\S.*\S)|(\S*)"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="UponError" default="Stop">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:enumeration value="Stop"/>
															<xs:enumeration value="Continue"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="ExecutionOrder">
													<xs:simpleType>
														<xs:restriction base="xs:integer">
															<xs:minInclusive value="1"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="DisplayGroup" type="xs:string"/>
											</xs:complexType>
										</xs:element>
										<xs:element ref="Dependencies" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Uninstall" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Component" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="OnlyOn" minOccurs="0">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="UnitName" maxOccurs="unbounded">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:minLength value="1"/>
																			<xs:pattern value="(\S.*\S)|(\S*)"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="Name" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:minLength value="1"/>
															<xs:pattern value="(\S.*\S)|(\S*)"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="UponError" default="Stop">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:enumeration value="Stop"/>
															<xs:enumeration value="Continue"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="ExecutionOrder">
													<xs:simpleType>
														<xs:restriction base="xs:integer">
															<xs:minInclusive value="1"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="DisplayGroup" type="xs:string"/>
											</xs:complexType>
										</xs:element>
										<xs:element ref="Dependencies" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Upgrade" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Component" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="OnlyOn" minOccurs="0">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="UnitName" maxOccurs="unbounded">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:minLength value="1"/>
																			<xs:pattern value="(\S.*\S)|(\S*)"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="Name" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:minLength value="1"/>
															<xs:pattern value="(\S.*\S)|(\S*)"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="UponError" default="Stop">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:enumeration value="Stop"/>
															<xs:enumeration value="Continue"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="ExecutionOrder">
													<xs:simpleType>
														<xs:restriction base="xs:integer">
															<xs:minInclusive value="1"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="DisplayGroup" type="xs:string"/>
												<xs:attribute name="ForceOperation">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:enumeration value="Install"/>
															<xs:enumeration value="Uninstall"/>
															<xs:enumeration value="Upgrade"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
										<xs:element ref="Dependencies" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Rollback" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Component" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="OnlyOn" minOccurs="0">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="UnitName" maxOccurs="unbounded">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:minLength value="1"/>
																			<xs:pattern value="(\S.*\S)|(\S*)"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="Name" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:minLength value="1"/>
															<xs:pattern value="(\S.*\S)|(\S*)"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="UponError" default="Stop">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:enumeration value="Stop"/>
															<xs:enumeration value="Continue"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="ExecutionOrder">
													<xs:simpleType>
														<xs:restriction base="xs:integer">
															<xs:minInclusive value="1"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="DisplayGroup" type="xs:string"/>
												<xs:attribute name="ForceOperation">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:enumeration value="Install"/>
															<xs:enumeration value="Uninstall"/>
															<xs:enumeration value="Upgrade"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
										<xs:element ref="Dependencies" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Parameters" minOccurs="0">
								<xs:complexType>
									<xs:choice maxOccurs="unbounded">
										<xs:element name="Parameter" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Value" minOccurs="0"/>
												</xs:sequence>
												<xs:attribute name="Overwrite" type="xs:boolean" default="true"/>
												<xs:attribute name="Display" type="xs:boolean" default="true"/>
												<xs:attributeGroup ref="ParameterAttributesGroup"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="Alias" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Value" minOccurs="0"/>
													<xs:element name="Restrictions">
														<xs:complexType>
															<xs:all>
																<xs:element name="Type">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:enumeration value="Number"/>
																			<xs:enumeration value="String"/>
																			<xs:enumeration value="Password"/>
																			<xs:enumeration value="Enum"/>
																			<xs:enumeration value="Boolean"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="MinVal" type="xs:integer" minOccurs="0"/>
																<xs:element name="MaxVal" type="xs:integer" minOccurs="0"/>
																<xs:element name="MinLength" type="xs:integer" minOccurs="0"/>
																<xs:element name="MaxLength" type="xs:integer" minOccurs="0"/>
																<xs:element name="Pattern" minOccurs="0">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:minLength value="1"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="Enum" minOccurs="0">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="Item" maxOccurs="unbounded">
																				<xs:complexType>
																					<xs:attribute name="Display" type="xs:string">
																						<xs:annotation>
																							<xs:documentation>The name which will be displayed in the WUI</xs:documentation>
																						</xs:annotation>
																					</xs:attribute>
																					<xs:attribute name="Value" type="xs:string" use="required"/>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
																<xs:element name="Mandatory" type="xs:boolean" default="false" minOccurs="0">
																	<xs:annotation>
																		<xs:documentation>Determines whether the parameter value is mandatory or not.</xs:documentation>
																	</xs:annotation>
																</xs:element>
															</xs:all>
														</xs:complexType>
													</xs:element>
													<xs:element name="Parameter" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attributeGroup ref="ParameterAttributesGroup"/>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="DisplayName" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:minLength value="1"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="Overwrite" type="xs:boolean"/>
												<xs:attribute name="Display" type="xs:boolean" default="true"/>
											</xs:complexType>
										</xs:element>
									</xs:choice>
								</xs:complexType>
							</xs:element>
							<xs:element ref="Dependencies" minOccurs="0"/>
						</xs:all>
						<xs:attribute name="Name" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:minLength value="1"/>
									<xs:pattern value="(\S.*\S)|(\S*)"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="Platform" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="Linux"/>
									<xs:enumeration value="SunOS"/>
									<xs:enumeration value="AIX"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="ParameterAttributesGroup">
		<xs:attribute name="Name" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ComponentName" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:pattern value="(\S.*\S)|(\S*)"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:attributeGroup>
	<xs:element name="ExecutionOrder">
		<xs:complexType>
			<xs:attribute name="Number" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Dependencies">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Component" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Component">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DependsOn">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Component" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attributeGroup ref="ComponentAttributesGroup"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attributeGroup ref="ComponentAttributesGroup"/>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="ComponentAttributesGroup">
		<xs:attribute name="UnitName" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:pattern value="(\S.*\S)|(\S*)"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Name" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
					<xs:pattern value="(\S.*\S)|(\S*)"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:attributeGroup>
</xs:schema>

=== dkreda/MyPerlProject/Integration/Projects/AddService_OMAP/VI_SWIM_Integ/Build/AddService/NDU-WHC/OMU_Group-UAF.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 (http://www.altova.com) by XMLSpy 2007 Professional Ed., Installed for 43 users (Comvers) -->
<SWIM xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\DOCUME~1\dkreda\MYDOCU~1\Integration\Projects\SwimConvertor\CAFTests\UAF.xsd">
  <UnitType Name="OMU_Group" Platform="Linux">
    <Install>
      <Component Name="WHC_Service_OMU" ExecutionOrder="210">
<!--This Component has Product Name WHC_FTM_Config_2 with ExecutionPhass 162-->
<!--This Component has Product Name WHC_Compas_Config with ExecutionPhass 210-->
<!--This Component has Product Name WHC_Balancer_Config_OMU with ExecutionPhass 150-->
<!--This Component has Product Name WHC_Fixes with ExecutionPhass 150-->
<!--This Component has Product Name WHC_TCM_Config with ExecutionPhass 150-->
<!--This Component has Product Name Uninstall_Marimba with ExecutionPhass 150-->
<!--This Component has Product Name WHC_FTM_Config_1 with ExecutionPhass 160-->
      </Component>
<!--This Component has Product Name WhoCalled_profile_definition with ExecutionPhass 150-->
      <Component Name="ProfileDefinition_Compas" ExecutionOrder="250"/>
      <Component Name="UpdateTopology" ExecutionOrder="260"/>
    </Install>
    <Parameters>
      <Parameter Name="RunUnit" ComponentName="UpdateTopology" Display="false">
        <Value>{LocalIP}</Value>
      </Parameter>
    </Parameters>
  </UnitType>
</SWIM>

=== dkreda/MyPerlProject/Integration/Projects/Swim_CreateSys/tmp185/OMU_Group-UAF.xml
<?xml version="1.0" encoding="UTF-8"?>
<SWIM xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\DOCUME~1\dkreda\Desktop\UAF.xsd">
  <UnitType Name="OMU_Group" Platform="Linux">
<!--This UAF is implementation of Marimba ServerGroup OMU-->
    <Install>
      <Component Name="Config_IS4_Balancers_Deployments" ExecutionOrder="10">
        <OnlyOn>
          <UnitName>Balancer</UnitName>
        </OnlyOn>
      </Component>
      <Component Name="ProfileDefinition_Compas" ExecutionOrder="100"/>
      <Component Name="Config_OMU_Deployments" ExecutionOrder="100"/>
    </Install>
    <Parameters>
      <Parameter Name="UnitRun" ComponentName="Config_OMU_Deployments" Display="false">
        <Value>OMU</Value>
      </Parameter>
    </Parameters>
  </UnitType>
</SWIM>

=== dkreda/MyPerlProject/Integration/Projects/SWIMDemo/CreateSys/Build/Common/VI/CAS_Group-UAF.xml
<?xml version="1.0" encoding="UTF-8"?>
<SWIM xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\DOCUME~1\galcohe\Desktop\VI_SUITE_SWIM\UAF.xsd">
	<UnitType Name="CAS_Group" Platform="Linux">
		<Install>
			<Component Name="genesis" ExecutionOrder="210">
				<!--This Component has Product Name Genesis-JGlue with ExecutionPhass 210-->
				<!--This Component has Product Name Genesis-BASE with ExecutionPhass 190-->
			</Component>
			<Component Name="mts" ExecutionOrder="170">
				<!--This Component has Product Name MTS with ExecutionPhass 170-->
			</Component>
			<Component Name="um23log" ExecutionOrder="152">
				<!--This Component has Product Name NciLi with ExecutionPhass 152-->
				<!--This Component has Product Name VfpApi with ExecutionPhass 150-->
			</Component>
            <Component Name="VI_AUDIT" ExecutionOrder="4990">
				<!--This Component has Product Name swp-CSPbase-Services with ExecutionPhass 4990-->
				<!--This Component has Product Name change_traceability_params with ExecutionPhass 160-->
				<!--This Component has Product Name enable_disable_traceability with ExecutionPhass 170-->
			</Component>
			<Component Name="VI_CSP-Base_Customization_CAS" ExecutionOrder="110">
				<!--This Component has Product Name VI_CSP-Base_Customization with ExecutionPhass 110-->
				<!--This Component has Product Name VI_CSP-MTA_Custom with ExecutionPhass 110-->
			</Component>
            <Component Name="CSP_Base_Linux" ExecutionOrder="70">
				<!--This Component has Product Name CSPbase_Post_Reboot with ExecutionPhass 70-->
				<!--This Component has Product Name CSPbase with ExecutionPhass 60-->
			</Component>
			<Component Name="vi_j2sdk" ExecutionOrder="100">
				<!--This Component has Product Name JRE_Gen_32bits with ExecutionPhass 100-->
			</Component>
			<Component Name="vi_mta_CAS" ExecutionOrder="252">
				<!--This Component has Product Name MTA_BASE with ExecutionPhass 250-->
				<!--This Component has Product Name MTA_CAS with ExecutionPhass 252-->
			</Component>
			<Component Name="aumsi_CAS" ExecutionOrder="190">
				<!--This Component has Product Name AUMSI with ExecutionPhass 190-->
			</Component>
			<Component Name="Aumsi4Vvm_CAS" ExecutionOrder="190">
				<!--This Component has Product Name IPhoneConfig with ExecutionPhass 190-->
			</Component>
			<Component Name="MTA_Plugin_CAS" ExecutionOrder="550">
				<!--This Component has Product Name MTA_Plugin_CAS with ExecutionPhass 550-->
				<!--This Component has Product Name MTA_Plugin with ExecutionPhass 250-->
			</Component>
			<Component Name="webinbox_CAS" ExecutionOrder="230">
				<!--This Component has Product Name WebInbox-WIS with ExecutionPhass 230-->
			</Component>
			<Component Name="um_utils" ExecutionOrder="150">
				<!--This Component has Product Name UM_UTILS with ExecutionPhass 150-->
			</Component>
			<Component Name="Babysitter" ExecutionOrder="150">
				<!--This Component has Product Name Babysitter with ExecutionPhass 150-->
			</Component>
			<Component Name="service-kit-vi_suite_CAS" ExecutionOrder="3150">
				<!--This Component has Product Name Merge_Tool with ExecutionPhass 150-->
				<!--This Component has Product Name IC-IFS_CAS_Balancer_Farms with ExecutionPhass 2150-->
				<!--This Component has Product Name Platform_Config with ExecutionPhass 2154-->
				<!--This Component has Product Name Maintanenc_Product with ExecutionPhass 150-->
				<!--This Component has Product Name GEN_Customization with ExecutionPhass 2156-->
				<!--This Component has Product Name MTS_Customization_Not_Per_HW with ExecutionPhass 3150-->
				<!--This Component has Product Name Platform_Install with ExecutionPhass 250-->
				<!--This Component has Product Name Service_Config with ExecutionPhass 2152-->
			</Component>
      <Component Name="Reboot" ExecutionOrder="200000">
      </Component>
			<Component Name="service-kit-vi_suite_Balancer" ExecutionOrder="3200">
				<OnlyOn>
					<UnitName>Balancer</UnitName>
				</OnlyOn>
			</Component>
			<Component Name="balancer_MZ" ExecutionOrder="155">
				<OnlyOn>
					<UnitName>Balancer</UnitName>
				</OnlyOn>
			</Component>
			<Component Name="Linux_Hkit" ExecutionOrder="150000">
				<!--This Component has Product Name SEC_AS5_HKIT with ExecutionPhass 150-->
			</Component>
			<Component Name="Tomcat" ExecutionOrder="150">
				<!--This Component has Product Name Tomcat with ExecutionPhass 150-->
			</Component>
      <Component Name="VI_SiteBook_CAS" ExecutionOrder="200">
 <!-- This Component has Product Name create_sitebook_user with ExecutionPhass 330
  --> 
			</Component>
		</Install>
		<Uninstall>
			<Component Name="genesis"/>
			<Component Name="mts"/>
      <Component Name="VI_SiteBook_CAS"/>
			<Component Name="vi_mta_CAS"/>
			<Component Name="aumsi_CAS"/>
			<Component Name="MTA_Plugin_CAS"/>
			<Component Name="webinbox_CAS"/>
			<Component Name="um_utils"/>
			<Component Name="balancer"/>
			<Component Name="Tomcat"/>
		</Uninstall>
		<Parameters>
			<Parameter Name="Unit_Type" ComponentName="genesis" Display="false">
				<Value>CAS</Value>
			</Parameter>
			<Parameter Name="UnitType" ComponentName="MTA_Plugin_CAS" Display="false">
				<Value>CAS</Value>
			</Parameter>
			<Parameter Name="Unit_Type" ComponentName="vi_mta_CAS" Display="false">
				<Value>CAS</Value>
			</Parameter>
			   <Parameter Name="UnitType" ComponentName="vi_mta_CAS" Display="false">
                        </Parameter>
			<Parameter Name="Unit_Type" ComponentName="Babysitter" Display="false">
				<Value>CAS</Value>
			</Parameter>
			<Parameter Name="Unit type" ComponentName="MTA_Plugin_CAS" Display="false">
				<Value>CAS</Value>
			</Parameter>
		</Parameters>
	</UnitType>
</SWIM>
